version: '3'

networks:
  example:
    driver: bridge
services:
  db:
    image: mariadb:10.5
    ports:
      - "3308:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: Pass1word
    restart: on-failure
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - example
  migrate-rules-db:
    image: registry.sasyadev.com/migrate_wait:latest
    command: -c "waitforit -timeout=30 -retry=1000 -debug -address=tcp://db:3306 -- echo starting migration && migrate -path=/migrations -database mysql://root:Pass1word@tcp\(db:3306\)/rules up"
    volumes:
      - ../../compliance-hub-rules-service/database/migrations:/migrations
    networks:
      - example
  
